"""create production_observations table

Revision ID: 6c446741b3cb
Revises: feb581a43eff
Create Date: 2026-09-08 18:17:28.945211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c446741b3cb'
down_revision: Union[str, None] = 'feb581a43eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_value', sa.String(length=1000), nullable=True),
    sa.Column('parsed_numeric', sa.Float(), nullable=True),
    sa.Column('parsed_category', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('valid', 'missing', 'invalid', 'unseen_category', name='observation_status'), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_observations_feature_id'), 'production_observations', ['feature_id'], unique=False)
    op.create_index(op.f('ix_production_observations_ingested_at'), 'production_observations', ['ingested_at'], unique=False)
    op.create_index(op.f('ix_production_observations_model_version_id'), 'production_observations', ['model_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_observations_model_version_id'), table_name='production_observations')
    op.drop_index(op.f('ix_production_observations_ingested_at'), table_name='production_observations')
    op.drop_index(op.f('ix_production_observations_feature_id'), table_name='production_observations')
    op.drop_table('production_observations')
    # ### end Alembic commands ###
