"""create monitoring_jobs table

Revision ID: 8d0d24068219
Revises: 37da8c39f724
Create Date: 2026-09-09 05:25:54.011574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d0d24068219'
down_revision: Union[str, None] = '37da8c39f724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('drift_run_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='monitoring_job_status'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['drift_run_id'], ['drift_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_monitoring_jobs_model_version_id'), 'monitoring_jobs', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_monitoring_jobs_schedule_id'), 'monitoring_jobs', ['schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitoring_jobs_schedule_id'), table_name='monitoring_jobs')
    op.drop_index(op.f('ix_monitoring_jobs_model_version_id'), table_name='monitoring_jobs')
    op.drop_table('monitoring_jobs')
    # ### end Alembic commands ###
