"""create monitoring_schedules table and add FK on monitoring_jobs.schedule_id

Revision ID: 9243b4ae8cbc
Revises: 8d0d24068219
Create Date: 2026-09-09 05:57:37.891756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9243b4ae8cbc'
down_revision: Union[str, None] = '8d0d24068219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('interval', sa.Enum('hourly', 'every_6_hours', 'daily', name='schedule_interval'), nullable=False),
    sa.Column('reference_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_snapshot_id'], ['reference_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_schedules_model_version_id'), 'monitoring_schedules', ['model_version_id'], unique=False)
    op.create_foreign_key(None, 'monitoring_jobs', 'monitoring_schedules', ['schedule_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'monitoring_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_monitoring_schedules_model_version_id'), table_name='monitoring_schedules')
    op.drop_table('monitoring_schedules')
    # ### end Alembic commands ###
