"""create reference snapshot tables

Revision ID: feb581a43eff
Revises: 68b6989b0f88
Create Date: 2026-09-08 18:14:47.864615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb581a43eff'
down_revision: Union[str, None] = '68b6989b0f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_snapshots_model_version_id'), 'reference_snapshots', ['model_version_id'], unique=False)
    op.create_table('reference_raw_categoricals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('category_value', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_snapshot_id'], ['reference_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_raw_categoricals_feature_id'), 'reference_raw_categoricals', ['feature_id'], unique=False)
    op.create_index(op.f('ix_reference_raw_categoricals_reference_snapshot_id'), 'reference_raw_categoricals', ['reference_snapshot_id'], unique=False)
    op.create_table('reference_raw_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_snapshot_id'], ['reference_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_raw_samples_feature_id'), 'reference_raw_samples', ['feature_id'], unique=False)
    op.create_index(op.f('ix_reference_raw_samples_reference_snapshot_id'), 'reference_raw_samples', ['reference_snapshot_id'], unique=False)
    op.create_table('reference_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('statistics', sa.JSON(), nullable=False),
    sa.Column('n_valid', sa.Integer(), nullable=False),
    sa.Column('n_missing', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_snapshot_id'], ['reference_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_snapshot_id', 'feature_id', name='uq_reference_stats_snapshot_feature')
    )
    op.create_index(op.f('ix_reference_stats_feature_id'), 'reference_stats', ['feature_id'], unique=False)
    op.create_index(op.f('ix_reference_stats_reference_snapshot_id'), 'reference_stats', ['reference_snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_stats_reference_snapshot_id'), table_name='reference_stats')
    op.drop_index(op.f('ix_reference_stats_feature_id'), table_name='reference_stats')
    op.drop_table('reference_stats')
    op.drop_index(op.f('ix_reference_raw_samples_reference_snapshot_id'), table_name='reference_raw_samples')
    op.drop_index(op.f('ix_reference_raw_samples_feature_id'), table_name='reference_raw_samples')
    op.drop_table('reference_raw_samples')
    op.drop_index(op.f('ix_reference_raw_categoricals_reference_snapshot_id'), table_name='reference_raw_categoricals')
    op.drop_index(op.f('ix_reference_raw_categoricals_feature_id'), table_name='reference_raw_categoricals')
    op.drop_table('reference_raw_categoricals')
    op.drop_index(op.f('ix_reference_snapshots_model_version_id'), table_name='reference_snapshots')
    op.drop_table('reference_snapshots')
    # ### end Alembic commands ###
